# Imports

In [1]:
import numpy as np
import pandas as pd
import nfl_data_py as nfl

/var/folders/yx/gjm2fjs56vl5kkwrb6xf5d2h0000gn/T/ipykernel_47312/4201646983.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# Importing NFL Data

## PFR Data

In [7]:
pfr_years = range(2018, 2023 + 1)
df_pfr_pass = nfl.import_seasonal_pfr("pass", pfr_years)

In [9]:
df_pfr_pass.head()

,player,team,pass_attempts,throwaways,spikes,drops,drop_pct,bad_throws,bad_throw_pct,season,...,on_tgt_throws,on_tgt_pct,rpo_plays,rpo_yards,rpo_pass_att,rpo_pass_yards,rpo_rush_att,rpo_rush_yards,pa_pass_att,pa_pass_yards
0,Ben Roethlisberger,PIT,675.0,7.0,3.0,24.0,3.6,122.0,18.3,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Patrick Mahomes,KC,580.0,24.0,1.0,28.0,5.0,95.0,17.1,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Matt Ryan,ATL,608.0,18.0,1.0,36.0,6.1,79.0,13.4,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jared Goff,LAR,561.0,29.0,2.0,13.0,2.5,93.0,17.5,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andrew Luck,IND,639.0,8.0,2.0,37.0,5.9,88.0,14.0,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_pfr_rec = nfl.import_seasonal_pfr("rec", pfr_years)

In [12]:
df_pfr_rec.columns

Index(['season', 'player', 'pfr_id', 'tm', 'age', 'pos', 'g', 'gs', 'tgt',
       'rec', 'yds', 'td', 'x1d', 'ybc', 'ybc_r', 'yac', 'yac_r', 'adot',
       'brk_tkl', 'rec_br', 'drop', 'drop_percent', 'int', 'rat', 'loaded'],
      dtype='object')

In [11]:
df_pfr_rec.head()

,season,player,pfr_id,tm,age,pos,g,gs,tgt,rec,...,yac,yac_r,adot,brk_tkl,rec_br,drop,drop_percent,int,rat,loaded
0,2018,Michael Thomas,ThomMi05,NO,25.0,WR,16.0,16.0,147.0,125.0,...,514.0,4.1,7.7,6.0,20.8,3.0,0.020,1.0,124.1,2023-08-21
1,2018,Zach Ertz,ErtzZa00,PHI,28.0,TE,16.0,16.0,156.0,116.0,...,353.0,3.0,7.2,3.0,38.7,5.0,0.032,5.0,98.9,2023-08-21
2,2018,DeAndre Hopkins,HopkDe00,HOU,26.0,WR,16.0,16.0,163.0,115.0,...,387.0,3.4,11.5,5.0,23.0,2.0,0.012,3.0,115.9,2023-08-21
3,2018,Julio Jones,JoneJu02,ATL,29.0,WR,16.0,16.0,170.0,113.0,...,448.0,4.0,14.0,3.0,37.7,9.0,0.053,3.0,106.9,2023-08-21
4,2018,Adam Thielen,ThieAd00,MIN,28.0,WR,16.0,16.0,153.0,113.0,...,416.0,3.7,9.4,3.0,37.7,3.0,0.020,2.0,115.2,2023-08-21

In [14]:
df_pfr_rec.query('player == "Mike Evans"')

,season,player,pfr_id,tm,age,pos,g,gs,tgt,rec,...,yac,yac_r,adot,brk_tkl,rec_br,drop,drop_percent,int,rat,loaded
16,2018,Mike Evans,EvanMi00,TB,25.0,WR,16.0,16.0,138.0,86.0,...,282.0,3.3,15.6,0.0,NaN,7.0,0.051,8.0,95.2,2023-08-21
554,2019,Mike Evans,EvanMi00,TB,26.0,WR,13.0,13.0,118.0,67.0,...,256.0,3.8,15.1,3.0,22.3,7.0,0.059,8.0,84.6,2023-08-21
1058,2020,Mike Evans,EvanMi00,TB,27.0,WR,16.0,16.0,109.0,70.0,...,265.0,3.8,12.1,2.0,35.0,4.0,0.037,2.0,126.0,2023-08-21
1580,2021,Mike Evans,EvanMi00,TB,28.0,WR,16.0,16.0,114.0,74.0,...,259.0,3.5,13.0,2.0,37.0,2.0,0.018,3.0,122.6,2023-08-21
2110,2022,Mike Evans,EvanMi00,TB,29.0,WR,15.0,15.0,127.0,77.0,...,216.0,2.8,12.6,2.0,38.5,4.0,0.031,6.0,85.5,2023-08-28
2617,2023,Mike Evans,EvanMi00,TB,30.0,WR,17.0,17.0,136.0,79.0,...,322.0,4.1,14.0,2.0,39.5,7.0,0.051,3.0,111.6,2024-02-29

## Snap Percentage

In [5]:
snap_years = range(2012, 2023 + 1)
df_snaps = nfl.import_snap_counts(snap_years)

In [8]:
df_snaps.head()

,game_id,pfr_game_id,season,game_type,week,player,pfr_player_id,position,team,opponent,offense_snaps,offense_pct,defense_snaps,defense_pct,st_snaps,st_pct
0,2012_01_ATL_KC,201209090kan,2012,REG,1,Branden Albert,AlbeBr20,T,KC,ATL,69.0,1.0,0.0,0.0,5.0,0.17
1,2012_01_ATL_KC,201209090kan,2012,REG,1,Rodney Hudson,HudsRo00,C,KC,ATL,69.0,1.0,0.0,0.0,5.0,0.17
2,2012_01_ATL_KC,201209090kan,2012,REG,1,Jon Asamoah,AsamJo20,G,KC,ATL,69.0,1.0,0.0,0.0,5.0,0.17
3,2012_01_ATL_KC,201209090kan,2012,REG,1,Ryan Lilja,LiljRy20,G,KC,ATL,69.0,1.0,0.0,0.0,5.0,0.17
4,2012_01_ATL_KC,201209090kan,2012,REG,1,Eric Winston,WinsEr20,T,KC,ATL,69.0,1.0,0.0,0.0,5.0,0.17

In [17]:
df_snaps.query("player == 'Mike Evans'") \
    .groupby(by='season') \
    .agg({"offense_snaps": "sum", "offense_pct": "mean"})

        offense_snaps  offense_pct
season
2014            769.0     0.831333
2015            858.0     0.838667
2016            946.0     0.834375
2017            881.0     0.866000
2018            939.0     0.843750
2019            792.0     0.849231
2020           1087.0     0.808000
2021           1038.0     0.827778
2022           1002.0     0.848750
2023            974.0     0.791053

## FTN Data

In [20]:
ftn_years = range(2022, 2023 + 1)
df_ftn = nfl.import_ftn_data(ftn_years)

Downcasting floats.

In [22]:
df_ftn.head()

,ftn_game_id,nflverse_game_id,season,week,ftn_play_id,nflverse_play_id,starting_hash,qb_location,n_offense_backfield,n_defense_box,...,read_thrown,is_catchable_ball,is_contested_ball,is_created_reception,is_drop,is_qb_sneak,n_blitzers,n_pass_rushers,is_qb_fault_sack,date_pulled
0,5879,2022_01_BUF_LA,2022,1,963918,56,R,S,1.0,6,...,1,True,False,False,False,False,0,4.0,False,2024-01-24 14:37:20.981130+00:00
1,5879,2022_01_BUF_LA,2022,1,963919,80,R,S,1.0,6,...,None,False,False,False,False,False,0,4.0,False,2024-01-24 14:37:20.981130+00:00
2,5879,2022_01_BUF_LA,2022,1,963920,101,R,U,1.0,7,...,None,False,False,False,False,False,0,0.0,False,2024-01-24 14:37:20.981130+00:00
3,5879,2022_01_BUF_LA,2022,1,963921,122,R,S,2.0,6,...,CHK,True,False,False,False,False,1,5.0,False,2024-01-24 14:37:20.981130+00:00
4,5879,2022_01_BUF_LA,2022,1,963922,146,R,S,1.0,6,...,None,False,False,False,False,False,0,0.0,False,2024-01-24 14:37:20.981130+00:00

In [23]:
df_ftn.columns

Index(['ftn_game_id', 'nflverse_game_id', 'season', 'week', 'ftn_play_id',
       'nflverse_play_id', 'starting_hash', 'qb_location',
       'n_offense_backfield', 'n_defense_box', 'is_no_huddle', 'is_motion',
       'is_play_action', 'is_screen_pass', 'is_rpo', 'is_trick_play',
       'is_qb_out_of_pocket', 'is_interception_worthy', 'is_throw_away',
       'read_thrown', 'is_catchable_ball', 'is_contested_ball',
       'is_created_reception', 'is_drop', 'is_qb_sneak', 'n_blitzers',
       'n_pass_rushers', 'is_qb_fault_sack', 'date_pulled'],
      dtype='object')

# Win Totals

In [2]:
years = range(1999, 2023 + 1)

In [5]:
df_wins = nfl.import_win_totals(years)

WARNING:root:The win totals data source is currently in flux and may be out of date.

In [6]:
df_wins

,game_id,market_type,abbr,lines,odds,opening_lines,opening_odds,book,season
0,2006_04_ARI_ATL,money_line,ATL,NaN,-345,NaN,NaN,5Dimes,2006
1,2006_04_ARI_ATL,money_line,ATL,NaN,-345,NaN,NaN,sportbet,2006
2,2006_04_ARI_ATL,money_line,ARI,NaN,285,NaN,NaN,5Dimes,2006
3,2006_04_ARI_ATL,money_line,ARI,NaN,285,NaN,NaN,sportbet,2006
4,2006_04_ARI_ATL,money_line,ATL,NaN,-380,NaN,NaN,bet365,2006
...,...,...,...,...,...,...,...,...,...
478076,2021_18_WAS_NYG,total,over,38.5,-114,39.0,-115.0,BETMANIA,2021
478077,2021_18_WAS_NYG,total,under,38.5,-103,39.0,-102.0,SKYBOOK,2021
478078,2021_18_WAS_NYG,total,over,38.5,-117,39.0,-118.0,SKYBOOK,2021
478079,2021_18_WAS_NYG,total,under,38.5,-111,38.5,-111.0,BetRegal,2021
478080,2021_18_WAS_NYG,total,over,38.5,-111,38.5,-111.0,BetRegal,2021

# Scoring Lines

In [7]:
df_scoring_lines = nfl.import_sc_lines(years)

In [9]:
df_scoring_lines

      season  week away_team home_team     game_id side  line
0       2013     1       BAL       DEN  2013090500  BAL   7.5
1       2013     1       BAL       DEN  2013090500  DEN  -7.5
2       2013     1        NE       BUF  2013090800  BUF   9.5
3       2013     1        NE       BUF  2013090800   NE  -9.5
4       2013     1       SEA       CAR  2013090801  CAR   3.5
...      ...   ...       ...       ...         ...  ...   ...
4087    2020    17       JAX       IND  2021010313  JAX  14.0
4088    2020    17       ARI        LA  2021010314  ARI  -2.5
4089    2020    17       ARI        LA  2021010314   LA   2.5
4090    2020    17       SEA        SF  2021010315  SEA  -6.0
4091    2020    17       SEA        SF  2021010315   SF   6.0

[4092 rows x 7 columns]

# QBrs

In [12]:
qbr_years = range(2006, 2023 + 1)

In [31]:
df_qbr = nfl.import_qbr(qbr_years, level='nfl', frequency='season')

URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

In [32]:
df_qbr.columns

Index(['season', 'season_type', 'game_week', 'team_abb', 'player_id',
       'name_short', 'rank', 'qbr_total', 'pts_added', 'qb_plays', 'epa_total',
       'pass', 'run', 'exp_sack', 'penalty', 'qbr_raw', 'sack', 'name_first',
       'name_last', 'name_display', 'headshot_href', 'team', 'qualified'],
      dtype='object')

In [33]:
df_qbr[["season", "name_display", "qbr_total", "qbr_raw", "penalty", "exp_sack", "sack"]]

      season    name_display  qbr_total  qbr_raw  penalty  exp_sack  sack
0       2006  Peyton Manning       86.4     87.4      1.1         0  -5.0
1       2006       Tom Brady       68.6     67.2      2.8         0 -12.0
2       2006   Philip Rivers       67.4     67.6      0.3         0 -10.4
3       2006   Carson Palmer       67.1     66.4      2.5         0 -12.9
4       2006      Drew Brees       66.7     69.5      0.6         0  -7.7
...      ...             ...        ...      ...      ...       ...   ...
1358    2023  Jauan Jennings       99.2     99.0      0.0         0   0.0
1359    2023     Kareem Hunt       55.2     57.0      0.0         0   0.0
1360    2023   Isiah Pacheco       25.3     22.5      0.0         0   0.0
1361    2023   Sean Clifford       11.2      9.0      0.0         0   0.0
1362    2023     Davis Mills        0.1      0.1      0.0         0   0.0

[1363 rows x 7 columns]

In [34]:
df_qbr["exp_sack"].unique()

array([0])