In [2]:
import pandas as pd

In [3]:
df_core = pd.read_pickle("../../FantasyData/data-frames/df_basic_ngs_snaps_adv_1999_2023.pkl")

In [4]:
df_core.query("player_id == '00-0035150'")

Empty DataFrame
Columns: [player_id, season, season_type, completions, attempts, passing_yards, passing_tds, interceptions, sacks, sack_yards, sack_fumbles, sack_fumbles_lost, passing_air_yards, passing_yards_after_catch, passing_first_downs, passing_epa, passing_2pt_conversions, pacr, dakota, carries, rushing_yards, rushing_tds, rushing_fumbles, rushing_fumbles_lost, rushing_first_downs, rushing_epa, rushing_2pt_conversions, receptions, targets, receiving_yards, receiving_tds, receiving_fumbles, receiving_fumbles_lost, receiving_air_yards, receiving_yards_after_catch, receiving_first_downs, receiving_epa, receiving_2pt_conversions, racr, target_share, air_yards_share, wopr_x, special_teams_tds, fantasy_points, fantasy_points_ppr, games, tgt_sh, ay_sh, yac_sh, wopr_y, ry_sh, rtd_sh, rfd_sh, rtdfd_sh, dom, w8dom, yptmpa, ppr_sh, index, position, player_name, age, team, rank, tier, Draft Year, Draft No., Draft Round, Draft Pick, Draft Overall, Draft Team, College, avg_time_to_throw, avg_completed_air_yards, avg_intended_air_yards, avg_air_yards_differential, aggressiveness, max_completed_air_distance, avg_air_yards_to_sticks, pass_yards, pass_touchdowns, passer_rating, completion_percentage, expected_completion_percentage, completion_percentage_above_expectation, avg_air_distance, max_air_distance, efficiency, percent_attempts_gte_eight_defenders, avg_time_to_los, rush_attempts, rush_yards, expected_rush_yards, rush_yards_over_expected, avg_rush_yards, rush_yards_over_expected_per_att, rush_pct_over_expected, rush_touchdowns, avg_cushion, avg_separation, ...]
Index: []

[0 rows x 165 columns]

In [5]:
df = pd.read_csv("./pbp_participation_2023.csv")

In [6]:
df.columns

Index(['nflverse_game_id', 'old_game_id', 'play_id', 'possession_team',
       'offense_formation', 'offense_personnel', 'defenders_in_box',
       'defense_personnel', 'number_of_pass_rushers', 'players_on_play',
       'offense_players', 'defense_players', 'n_offense', 'n_defense',
       'ngs_air_yards', 'time_to_throw', 'was_pressure', 'route',
       'defense_man_zone_type', 'defense_coverage_type'],
      dtype='object')

In [7]:
df[["offense_personnel", "offense_players", "route", "n_offense", "possession_team"]].head(20)

,offense_personnel,offense_players,route,n_offense,possession_team
0,NaN,NaN,NaN,0,NaN
1,NaN,00-0035150;00-0037330;00-0036896;00-0033251;00...,NaN,11,ARI
2,"1 RB, 2 TE, 2 WR",00-0037746;00-0031095;00-0036334;00-0034445;00...,NaN,11,WAS
3,"1 RB, 1 TE, 3 WR",00-0037746;00-0031095;00-0036334;00-0034445;00...,HITCH,11,WAS
4,"1 RB, 1 TE, 3 WR",00-0031095;00-0036334;00-0034445;00-0031260;00...,NaN,11,WAS
5,"1 RB, 1 TE, 3 WR",00-0031095;00-0037746;00-0036334;00-0034445;00...,IN,11,WAS
6,"1 RB, 1 TE, 3 WR",00-0037746;00-0031095;00-0036334;00-0034445;00...,HITCH,11,WAS
7,"1 RB, 1 TE, 3 WR",00-0037746;00-0031095;00-0036334;00-0034445;00...,SCREEN,11,WAS
8,"1 RB, 1 TE, 3 WR",00-0031095;00-0036334;00-0034445;00-0031260;00...,HITCH,11,WAS
9,"1 RB, 1 TE, 3 WR",00-0031095;00-0036334;00-0034445;00-0031260;00...,FLAT,11,WAS
10,NaN,00-0036403;00-0038635;00-0039149;00-0031596;00...,NaN,11,WAS
11,"1 RB, 1 TE, 3 WR",00-0035662;00-0036936;00-0033676;00-0030061;00...,NaN,11,ARI
12,NaN,NaN,NaN,0,NaN
13,"1 RB, 2 TE, 2 WR",00-0035662;00-0033251;00-0033676;00-0030061;00...,NaN,11,ARI
14,"1 RB, 1 TE, 3 WR",00-0035662;00-0036936;00-0033676;00-0030061;00...,IN,11,ARI
15,"1 RB, 2 TE, 2 WR",00-0035662;00-0033251;00-0033676;00-0030061;00...,CROSS,11,ARI
16,"1 RB, 2 TE, 2 WR",00-0035662;00-0033676;00-0030061;00-0033949;00...,SCREEN,11,ARI
17,"1 RB, 1 TE, 3 WR",00-0035662;00-0036936;00-0033676;00-0030061;00...,NaN,11,ARI
18,NaN,00-0035150;00-0034473;00-0037330;00-0036896;00...,NaN,11,ARI
19,"1 RB, 1 TE, 3 WR",00-0031095;00-0037746;00-0036334;00-0034445;00...,NaN,11,WAS

In [20]:
for player in df.offense_players.iloc[1].split(";"):
    print(player)
    temp = df_core.query(f"player_id == '{player}' and season == 2023")
    if not temp.empty:
        print(temp[["player_name", "team"]])
        break

00-0035150
00-0037330
00-0036896
00-0033251
       player_name       team
11064  Zach Pascal  Cardinals